### ISSUE TITLE
Skeletonized baseplate generation fails with an error

### ISSUE THREAD

**Issue by Le0Michine** [Le0Michine/FusionGridfinityGenerator#41]
```
Error: An unknonwn error occurred, please validate your inputs and try again:
Traceback (most recent call last):
  File ".../FusionGridfinityGenerator\commands\commandCreateBaseplate\entry.py", line 313, in generateBaseplate
    baseplateBody = createGridfinityBaseplate(baseplateGeneratorInput, gridfinityBaseplateComponent)
  File ".../FusionGridfinityGenerator\lib\gridfinityUtils\baseplateGenerator.py", line 108, in createGridfinityBaseplate
    combineUtils.joinBodies(
  File ".../FusionGridfinityGenerator\lib\gridfinityUtils\combineUtils.py", line 36, in joinBodies
    combineFeature = targetComponent.features.combineFeatures.add(combineInput)
  File ".../Autodesk/webdeploy/production/ab436cfc442dca0a34652534c345f2bd00e2ba64/Api/Python/packages\adsk\fusion.py", line 14376, in add
    return _fusion.CombineFeatures_add(self, input)
RuntimeError: 5 : Some input argument is invalid.
```

In a new Fusion 360 2.0.16753 x86_64 this error occurs when trying to generate skeletonized baseplate. The reason is a change in how Fusion API handles circular pattern now. Before the body which was used to create the pattern wouldn't be included into the list for the resulting feature object, now this behavior changed so some adjustment is required to account for that.

**Comment by Le0Michine** [comment]
the fix is available in master branch now

**Comment by Le0Michine** [comment]
created prerelease with the fix https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.4.0
